CREATE (:Device {name: "Laptop", type: "Computer"})
CREATE (:Device {name: "Desktop PC", type: "Computer"})
CREATE (:Device {name: "Smartphone", type: "Mobile"})
CREATE (:Device {name: "Tablet", type: "Mobile"})
CREATE (:Device {name: "Smartwatch", type: "Wearable"})
CREATE (:Device {name: "Smart TV", type: "Entertainment"})
CREATE (:Device {name: "Gaming Console", type: "Entertainment"})
CREATE (:Device {name: "Digital Camera", type: "Photography"})
CREATE (:Device {name: "E-Reader", type: "Reading"})
CREATE (:Device {name: "Smart Speaker", type: "Audio"})
CREATE (:Device {name: "Fitness Tracker", type: "Health"})
CREATE (:Device {name: "Virtual Reality Headset", type: "Gaming"})
CREATE (:Device {name: "Smart Home Hub", type: "Home Automation"})
CREATE (:Device {name: "Network Switch", type: "Networking"})
CREATE (:Device {name: "USB Flash Drive", type: "Storage"})
CREATE (:Device {name: "External SSD", type: "Storage"})
CREATE (:Device {name: "Bluetooth Speaker", type: "Audio"})
CREATE (:Device {name: "Wireless Earbuds", type: "Audio"})
CREATE (:Device {name: "Smart Thermostat", type: "Home Automation"})
CREATE (:Device {name: "Smart Light Bulb", type: "Home Automation"})
CREATE (:Device {name: "Smart Lock", type: "Security"})
CREATE (:Device {name: "Smart Doorbell", type: "Security"})
CREATE (:Device {name: "Smart Camera", type: "Security"})
CREATE (:Device {name: "Smart Refrigerator", type: "Appliance"})
CREATE (:Device {name: "Smart Washing Machine", type: "Appliance"})
CREATE (:Device {name: "Smart Oven", type: "Appliance"})
CREATE (:Device {name: "Smart Coffee Maker", type: "Appliance"})
CREATE (:Device {name: "Smart Air Conditioner", type: "Appliance"})
CREATE (:Device {name: "Smart Vacuum Cleaner", type: "Appliance"})
CREATE (:Device {name: "Smart Air Purifier", type: "Appliance"})
CREATE (:Device {name: "Smart Water Leak Detector", type: "Security"})
CREATE (:Device {name: "Smart Smoke Detector", type: "Security"})
CREATE (:Device {name: "Smart Garage Door Opener", type: "Security"})
CREATE (:Device {name: "Smart Irrigation System", type: "Gardening"})
CREATE (:Device {name: "Smart Pet Feeder", type: "Pet Care"})
CREATE (:Device {name: "Smart Mirror", type: "Home Decor"})
CREATE (:Device {name: "Smart Scale", type: "Health"})
CREATE (:Device {name: "Smart Blood Pressure Monitor", type: "Health"})
CREATE (:Device {name: "Smart Glucose Monitor", type: "Health"})
CREATE (:Device {name: "Smart Sleep Tracker", type: "Health"})
CREATE (:Device {name: "Smart Air Quality Monitor", type: "Health"})           
CREATE (:Device {name: "Computer Monitor", type: "Display"})
CREATE (:Device {name: "Computer Mouse", type: "Input"})   
CREATE (:Device {name: "Printer", type: "Output"})
CREATE (:Device {name: "Scanner", type: "Input"})
CREATE (:Device {name: "Projector", type: "Display"})
CREATE (:Device {name: "Webcam", type: "Input"})
CREATE (:Device {name: "Speakers", type: "Output"})
CREATE (:Device {name: "External Hard Drive", type: "Storage"})
CREATE (:Device {name: "Network Router", type: "Networking"})  




