library("tm")
library("corpus")
library("SnowballC")
cname_jr <- file.path("/home/jigarpandya/my-dev/R/tagcloud/it-job-opportunities-dataset/data")
print(cname_jr)
print(dir(cname_jr))

text_corpus_jr <- Corpus(DirSource(cname_jr))
text_corpus_jr <- tm_map(text_corpus_jr, stripWhitespace)
text_corpus_jr <- tm_map(text_corpus_jr, content_transformer(tolower))
text_corpus_jr <- tm_map(text_corpus_jr, removeWords, stopwords("english"))
text_corpus_jr <- tm_map(text_corpus_jr, stemDocument)
text_corpus_jr <- tm_map(text_corpus_jr, removeNumbers)
text_corpus_jr <- tm_map(text_corpus_jr, removePunctuation)
dtm_jr <- DocumentTermMatrix(text_corpus_jr)
freq_jr <- sort(colSums(as.matrix(dtm_jr)), decreasing=TRUE)
head(freq_jr)
library(wordcloud)
wordcloud(names(freq_jr), freq_jr, min.freq=100)
