--------------------------------------------------------
--  File created - Saturday-July-15-2023   
--------------------------------------------------------
REM INSERTING into SCOTT.LOCATION_CONC_HIER
SET DEFINE OFF;
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (1,'earth',1,null);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (2,'Canada',2,1);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (3,'USA',2,1);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (4,'British Columbia',3,2);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (5,'Ontario',3,2);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (6,'New York',3,3);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (7,'Illinois',3,3);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (8,'Vancouver',4,4);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (9,'Victoria',4,4);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (10,'Toronto',4,5);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (11,'Ottawa',4,5);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (12,'NewYork City',4,6);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (13,'Buffalo',4,6);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (14,'Chicago',4,7);
Insert into SCOTT.LOCATION_CONC_HIER (LOCATION_ID,LOCATION_NAME,LOCATION_TYPE_ID,PARENT_LCH_ID) values (15,'Urbana',4,7);
